package com.geoknoesis.kastor.annotations

/**
 * Container annotation for multiple [PrefixMapping] annotations.
 * 
 * This annotation is automatically generated by the Kotlin compiler when
 * multiple [PrefixMapping] annotations are used on the same target. You typically
 * don't need to use this annotation directly.
 * 
 * Example usage (prefer using multiple @PrefixMapping annotations instead):
 * ```kotlin
 * @PrefixMappings([
 *     PrefixMapping(prefix = "foaf", namespace = "http://xmlns.com/foaf/0.1/"),
 *     PrefixMapping(prefix = "dct", namespace = "http://purl.org/dc/terms/")
 * ])
 * @RdfClass("foaf:Person")
 * data class Person(...)
 * ```
 * 
 * @param value Array of [PrefixMapping] annotations
 */
@Target(AnnotationTarget.CLASS, AnnotationTarget.FILE, AnnotationTarget.PACKAGE)
@Retention(AnnotationRetention.SOURCE)
annotation class PrefixMappings(
    val value: Array<PrefixMapping>
)