- name: "p2p-local"
  type: "p2p"
  enabled: true
  config:
    port: 4001
    discoveryEnabled: true
    bootstrapPeers: []
    enableMetrics: false

- name: "p2p-production"
  type: "p2p"
  enabled: false
  config:
    port: 4002
    discoveryEnabled: true
    bootstrapPeers:
      - "/ip4/192.168.1.100/tcp/4001/p2p/QmExamplePeer1"
      - "/ip4/192.168.1.101/tcp/4001/p2p/QmExamplePeer2"
    enableMetrics: true 