root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

plugins:
  - search
  - copy-code-button
  - theme-default
  - highlight
  - prism
  - github
  - gitbook-plugin-anchors
  - gitbook-plugin-advanced-emoji
  - gitbook-plugin-code
  - gitbook-plugin-ga
  - gitbook-plugin-sitemap

pluginsConfig:
  github:
    url: https://github.com/your-org/spatialwebnode
  ga:
    token: YOUR_GOOGLE_ANALYTICS_TOKEN
  sitemap:
    hostname: https://your-docs-domain.com
  prism:
    css:
      - prismjs/themes/prism-tomorrow.css
    lang:
      - kotlin
      - yaml
      - json
      - bash
      - dockerfile
      - xml

variables:
  version: "1.0.0"
  project_name: "hstpd"
  full_name: "HSTP (Hypermedia Spatial Transport Protocol) daemon" 